version: '3'

services:
  web:
    build:
      context: ./web/
      dockerfile: ./docker/alpine/Dockerfile
    container_name: web
    environment:
      - BACKEND_BASE_URL=http://localhost:8080
      - SUB_DIR=/
    ports:
      - 80:80

  php-web:
    container_name: migration
    build:
      context: ./infrastructure
      dockerfile: ./docker/migration/alpine/Dockerfile
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysqldb
      - DB_PORT=3306 
      - DB_DATABASE=DBpoppenhuis 
      - DB_USERNAME=laravel 
      - DB_PASSWORD=Azerty111
      - SUB_DIR=/
    ports:
      - "8080:80"
    depends_on:
      - mysqldb
    volumes:
      - ./images:/var/www/storage/app/public/

  mysqldb:
    build:
      context: ./infrastructure
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - ROOT_PASSWORD=Azerty123
      - DATABASE=DBpoppenhuis
      - EXTRA_USER=laravel
      - EXTRA_PASS=Azerty111
      - EXTRA_DATABASE=DBpoppenhuis
      - EXTRA_PERMISSIONS=ALL